language: php
php:
  - '8.0'
  - nightly
before_install:
  - pecl install ast
  - sudo apt-get install -y libffi-dev
install:
  - composer install
script:
  - vendor/bin/phan
  - vendor/bin/psalm
  - vendor/bin/phpcs
  - ./test.sh